### ISSUE TITLE
Incorrect no. of arguments

### ISSUE THREAD

**Issue by lukehinds** [lukehinds/anteater#8]
Traceback (most recent call last):
  File "/home/luke/repos/anteater/env/bin/anteater", line 6, in <module>
    from anteater.anteater import main
  File "/home/luke/repos/anteater/env/lib/python2.7/site-packages/anteater/anteater.py", line 26, in <module>
    from src.scan_tasks import scan_all, scan_project
  File "/home/luke/repos/anteater/env/lib/python2.7/site-packages/anteater/src/scan_tasks.py", line 25
    def scan_project(reports_dir, reports_dir, project):
SyntaxError: duplicate argument 'reports_dir' in function definition

**Comment by lukehinds** [comment]
Fix confirmed
